### ISSUE TITLE
PDF links are not clickable 

### ISSUE THREAD

**Issue by Soufianeelc** [BartoszJarocki/cv#16]

**Comment by mrgarciamanuel** [comment]
Can u explain in details all steps, how can i generate pdf files in this project?

**Comment by Soufianeelc** [comment]
For exemple if you visit [cv.jarocki.me](https://cv.jarocki.me/) and Press Ctrl + J, you will be able to download the CV as PDF. But the links(project links, social links...etc) aren't clickable.

**Comment by SujithThirumalaisamy** [comment]
Can you please provide some screenshots? It seems that your mentioned issue cannot be reproduced.

**Comment by mrgarciamanuel** [comment]
> For exemple if you visit [cv.jarocki.me](https://cv.jarocki.me/) and Press Ctrl + J, you will be able to download the CV as PDF. But the links(project links, social links...etc) aren't clickable.

The thing is that is this moment is not possible to click in Social media and project items in PDF files, maybe it should be new feature. The companies name is the only thing we're able to click and see their content in other other browser tab when export our cv PDF files.

**Comment by Soufianeelc** [comment]
Yes, but this won't stop me from not using it. I'm planning to use it to build my own resume. Thank you @BartoszJarocki for the great work 👍

**Comment by Louhii** [comment]
When converting your CV to a PDF, the hyperlinks become inactive if you just use a generic converter. I recommend using WonderShare, LightPDF or transferring your CV to Microsoft Word, then converting to a PDF as the software will keep the links.
https://pdf.wondershare.com/pdf-knowledge/hyperlinks-not-work-in-pdf.html#:~:text=That's%20probably%20because%20you%20have,from%20URLs%22%20enabled%20on%20Acrobat.

Link gives more info

**Comment by MonticolaExplorator** [comment]
I was experiencing the same issue, and fixed it selecting 'Save as PDF' instead of 'Print to PDF' on the Windows print menu (Windows 11, Edge)
![image](https://github.com/BartoszJarocki/cv/assets/90053345/07389f5a-0fc2-4ce8-a187-933d284acd04)
(Sorry, spanish here :))
