### ISSUE TITLE
Instructions for Installing, Preparing, and Deploying

### ISSUE THREAD

**Issue by inayet** [BartoszJarocki/cv#2]
Hi, can you include in the README.md file instructions on installing, preparing, and deploying this app. Thank you

**Comment by shiroyasha9** [comment]
Dude, it's literally a simple next.js project. 

To run it locally, all you do is

1. `yarn`
2. `yarn dev`

To deploy it, you follow Vercel's simple instructions - 
https://nextjs.org/learn-pages-router/basics/deploying-nextjs-app/deploy
Just a few button clicks basically.

**Comment by inayet** [comment]
@BartoszJarocki Thank you for adding those instructions to the README.md file. I got the local server up, how can we customize the cv with our information?

**Comment by SujithThirumalaisamy** [comment]
> @BartoszJarocki Thank you for adding those instructions to the README.md file. I got the local server up, how can we customize the cv with our information?

It is a straight forward thing to do. Just change the ```RESUME_DATA``` in the ```\src\data\resume-data.tsx``` file with your own data.

**Comment by OmitNomis** [comment]
The readme has been updated, this issue can be closed.
