### ISSUE TITLE
command button for small screen device

### ISSUE THREAD

**Issue by hemik000** [BartoszJarocki/cv#24]
![Screenshot 2023-12-30 135126](https://github.com/BartoszJarocki/cv/assets/19568116/d291e94c-aa9c-499a-a715-f654c1b1314a)

**Comment by shreyashrpawar** [comment]
approve the request for command button for small screen device. The small screen sized devices can see the windows icon to open the command pallet. Whereas there for the desktop devices, CTRL + J can be used for the same.

![image](https://github.com/BartoszJarocki/cv/assets/87687490/2aeebd3f-1cec-4098-a966-7d42e836aab4)
