### ISSUE TITLE
Adding save/export as pdf feature

### ISSUE THREAD

**Issue by movoid12** [BartoszJarocki/cv#3]
Really great resume website! It would be really cool and interesting to export/save the resume as pdf :) I will try to find a way doing that in the end of the resume. 

@all: Do you have any other recommended libraries to use instead of `react-pdf` library or is it good enough?

**Comment by BartoszJarocki** [comment]
project has special styles for printing so you can just use system print option ie. Cmd  +P on Mac and choose save as pdf 🙂

**Comment by movoid12** [comment]
Thanks @BartoszJarocki for your feedback. Yes thats a great option to save the resume as pdf on desktop but in case a user on smartphone or tablet and want to have the resume as pdf it would be useful to have that save button or do you think its not that necessary to implement that feature atm :) ?

**Comment by RaiPeter** [comment]
> Thanks @BartoszJarocki for your feedback. Yes thats a great option to save the resume as pdf on desktop but in case a user on smartphone or tablet and want to have the resume as pdf it would be useful to have that save button or do you think its not that necessary to implement that feature atm :) ?

Yes, this seems to be a good idea @movoid12

**Comment by SujithThirumalaisamy** [comment]
@BartoszJarocki I would like to work on this. 
##Proposal
1. Make the command in the footer item note as clickable with a note on that
2. Else, Change the text according to the screensize. using state ```isMobile```

Intrested to get you suggession on this..

**Comment by OmitNomis** [comment]
I feel like this is covered in #24 
and there's an MR adding a button to access the menu on mobile. 

I haven't checked it yet, and don't know if saving works on mobile, but the issues seem related.
