### ISSUE TITLE
Where's the data project's logo is used?

### ISSUE THREAD

**Issue by lamualfa** [BartoszJarocki/cv#38]
I don't see any use of the project's logo in either the screenshots or the code. Is it WIP?

https://github.com/BartoszJarocki/cv/blob/5c0a61989eb98cf0f240d5042ceda8457f2935f0/src/data/resume-data.tsx#L128

![image](https://github.com/BartoszJarocki/cv/assets/39755201/f48c6e35-c667-4b30-9de9-0f1df8f152cc)

**Comment by BartoszJarocki** [comment]
yes, wip
