### ISSUE TITLE
Does not pass ATS

### ISSUE THREAD

**Issue by RaphaelFakhri** [BartoszJarocki/cv#43]
The resulting pdf from this resume is 0% compatible with Automatic Tracking Systems. Is there a way to fix this so that they can read the words on the page?

**Comment by BartoszJarocki** [comment]
how can I debug this?

**Comment by RaphaelFakhri** [comment]
By passing the resulting pdf into an ATS software. I used an online one like jobscan.co, I am not knowledgeable on the avalability of this kind of software for local hosting.

**Comment by MarcinSkic** [comment]
What print option did you pick @RaphaelFakhri, at first I also had this problem but I fixed it by changing from `Microsoft print to PDF` to `Save as PDF`. In the first mode it is just an image of a website and text is not selectable, but in the second everything works fine and jobscan.co works properly.
