### ISSUE TITLE
Justify Align Text

### ISSUE THREAD

**Issue by TheoBearman** [BartoszJarocki/cv#49]
HI Bartosz,

Thank you for this repo.

I would like to have the ability to justify align text. Is there a way of doing this?

Thanks,

Theo

**Comment by ushiradineth** [comment]
You can use the tailwind classes `text-start`, `text-center` or `text-end`, to align your text, using this globally would have side effects that you need to fix manually, so best case scenario is to use it on each component as needed.

https://tailwindcss.com/docs/text-align

**Comment by TheoBearman** [comment]
Thanks!
