### ISSUE TITLE
Print removes grey outlines present around badges in design

### ISSUE THREAD

**Issue by 1amrishi** [BartoszJarocki/cv#61]
The print command seems to skip the grey rounded rectangles around the badges
<img width="743" alt="Screenshot 2024-02-15 at 9 08 27 PM" src="https://github.com/BartoszJarocki/cv/assets/120283735/cd0626f3-c6de-4654-8cb8-a4e1d1f15517">

**Comment by BartoszJarocki** [comment]
just check `print backgrounds` or something similar in print dialog settings
