### ISSUE TITLE
Need help with adding website link in resume

### ISSUE THREAD

**Issue by 1amrishi** [BartoszJarocki/cv#63]
Hello guys, am a noob in editing code, but tried and successfully deployed my site on vercel but need help with changing these top icons
<img width="466" alt="Screenshot 2024-02-26 at 9 08 13 PM" src="https://github.com/BartoszJarocki/cv/assets/120283735/38d5b9ca-cfe7-40c4-9bf2-ec3f1c29197f">

I want to add a website icon and a instagram icon and remove the twitter icon but whenever i try deployment fails due to some error, probably not getting the correct .tsx file for those logos

can anyone help

**Comment by muditbhargava66** [comment]
To update the social icons:

1. Import the icons you want to use from the icon pack in `resume-data.tsx`. For example:

```
import { GitHubIcon, LinkedInIcon, InstagramIcon, PersonIcon } from '@/components/icons';
```

2. Then update the social array in contact with the new icons:

```
contact: {
  social: [
    {
      name: "GitHub",
      url: "https://github.com/username",
      icon: GitHubIcon 
    },
    {
      name: "LinkedIn",
      url: "https://linkedin.com/in/username",
      icon: LinkedInIcon
    },
    {  
      name: "Instagram",
      url: "https://instagram.com/username",
      icon: InstagramIcon
    },
    {
      name: "Website", 
      url: "https://website.com",
      icon: PersonStandingIcon
    }
  ]
}
```

Let me know if that helps! I'm happy to clarify anything that's still unclear.

Hope this helps!

**Comment by 1amrishi** [comment]
what kind of file do i put in @/components/icons to import, which file format and from where to get them, i need instagaram icon and website icon

**Comment by 1amrishi** [comment]
> To update the social icons:
> 
> 1. Import the icons you want to use from the icon pack in `resume-data.tsx`. For example:
> 
> ```
> import { GitHubIcon, LinkedInIcon, InstagramIcon, PersonIcon } from '@/components/icons';
> ```
> 
> 2. Then update the social array in contact with the new icons:
> 
> ```
> contact: {
>   social: [
>     {
>       name: "GitHub",
>       url: "https://github.com/username",
>       icon: GitHubIcon 
>     },
>     {
>       name: "LinkedIn",
>       url: "https://linkedin.com/in/username",
>       icon: LinkedInIcon
>     },
>     {  
>       name: "Instagram",
>       url: "https://instagram.com/username",
>       icon: InstagramIcon
>     },
>     {
>       name: "Website", 
>       url: "https://website.com",
>       icon: PersonStandingIcon
>     }
>   ]
> }
> ```
> 
> Let me know if that helps! I'm happy to clarify anything that's still unclear.
> 
> Hope this helps!

what kind of file do i put in @/components/icons to import, which file format and from where to get them, i need instagaram icon and website icon

**Comment by Zekamashii** [comment]
You need to create your own InstagramIcon.tsx. It is something like this, but the path profile is pretty hard to get it right.


```typescript
export const InstagramIcon = (props: React.SVGProps<SVGSVGElement>) => {
    return (
      <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
        <title>Instagram</title>
        <path
          fill="currentColor"
          d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"
        />
      </svg>
    );
  };
```
